# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SleepSound' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SleepSound
  pod 'Reusable'
  pod 'Alamofire', '~>4.8'
  pod 'ObjectMapper'
  pod 'Toast'
  pod 'Kingfisher'

end
